### PR TITLE
Tutorial (single button)

### LINKED ISSUE #177: Make logo more colorful
Otherwise seems like something might be wrong; logo color is often used to signify "ON"

### PR DESCRIPTION
**Pull request by benfrancis314**
When install, creates opens up new page with a little tutorial button. 

Also darker load button, new colored logo, 

Close #177, #176,

### CODE REVIEW

File: extension/background.js [hunk 1]
```diff
@@ -16,39 +16,39 @@ chrome.runtime.onInstalled.addListener(function() {
...
+        - tab.pendingUrl is always equal to the demoUrl, so we cannot use it to see if we are succesfully at that tab yet. 
+        The stack overflow recommends using onUpdated, but this results in a listener that gets called for every tab update. 
+        You have to build a condition in there, except we cannot look for the URL, bc then it would happen every time we visit that url. 
+        And so on. This works for now, though it incurs an unwanted delay:
+        */
+        setTimeout(function() {
+                chrome.tabs.sendMessage(tab.id, {command: "startTutorial"}, function(response) {
+                    chrome.tabs.sendMessage(tab.id, {command: "toggleUITutorial"}, function(response) {})
+                });
+        }, 3000);
```
Comment (benfrancis314) [inline extension/background.js:50]: See above for commentary; this is a *very* hacky fix, but for the moment it appears to do the job.

File: extension/background.js [hunk 2]
```diff
@@ -16,39 +16,39 @@ chrome.runtime.onInstalled.addListener(function() {
...
-            top: 100,
-            width: 400,
-            height: 300,
-            type: "popup"
-        });
-    });
-});
\ No newline at end of file
+// Take user to survey after uninstall
+chrome.runtime.setUninstallURL("https://www.readerease.com/uninstall");
```
Comment (benfrancis314) [inline extension/background.js:56]: Just need to make this on website, but can be handled after-publish pre-approval.

File: extension/content_script.js [hunk 3]
```diff
@@ -273,6 +275,8 @@ function scrollToTracker(cb) {
 	// and that can be jarring. Be a little forgiving, let them "walk into" the reading band, like
 	// first level in Mario: https://www.youtube.com/watch?v=K-NBcP0YUQI. Experiment w value
 	const topPageForgiveness = 50;
+	// Above this is the reading timer; when scrolling up, don't let tracker get above this
+	const upperLimit = 35;
```
Comment (benfrancis314) [inline extension/content_script.js:279]: This is actually a separate issue; if only scroll up when user is going backward at top of page, we will have some text that is highlighted obscured by the reading timer.

File: extension/content_script.js [hunk 4]
```diff
@@ -635,21 +640,64 @@ function toggleExtensionVisibility() {
...
+			}			
+			if (request.command === "toggleUI") {
+				toggleApp();
+			}	
+			// TODO: This can be perhaps refactored. For now, it's an easy fir
+			else if (request.command === "toggleUITutorial") {
+				if (settings.getAppStatus()) {
+					return; // If app status is on, do nothing
+				} 
+				toggleApp();
```
Comment (benfrancis314) [inline extension/content_script.js:662]: The tutorial has different cases for if the persistent app status is on or off. This handles it, though perhaps not elegantly.

File: extension/content_script.js [hunk 5]
```diff
@@ -635,21 +640,64 @@ function toggleExtensionVisibility() {
...
+					tutorialPopup.remove()
+				});
+				$("#optionsButtonTutorial").click(function() {
+					$("#optionsButton").click();
+					tutorialPopup.remove();
+				})
+			}	
+		}	
+	);
+}
```
Comment (benfrancis314) [inline extension/content_script.js:693]: Screen Shot 2020-08-03 at 2 32 03 PM
Screen Shot 2020-08-03 at 2 31 57 PM

Second image is what it looks like when you hover over the check mark. Clicking on either gear or the checkmark will get rid of tutorial box

File: extension/content_script.js [hunk 6]
```diff
@@ -635,21 +640,64 @@ function toggleExtensionVisibility() {
...
+function removeTutorial() {
+	let pinPopup = $("#pinPopupContainer");
+	let tutorialPopup = $("#tutorialPopupContainer");
+	if (pinPopup) { pinPopup.remove() }
+	if (tutorialPopup) { tutorialPopup.remove() }
+}
+
```
Comment (benfrancis314) [inline extension/content_script.js]: Screen Shot 2020-08-03 at 2 31 57 PM
Screen Shot 2020-08-03 at 2 32 03 PM

Second is what it looks like when you hover over the check mark

File: extension/lib/time_tracker_view.js [hunk 7]
```diff
@@ -128,13 +128,7 @@ class TimeTrackerView {
...
-                        </g>
-                    </g>
-                </svg>
+                ${window.gearLogo}
```
Comment (benfrancis314) [inline extension/lib/time_tracker_view.js:131]: Moved gear SVG into separate file, so can reuse for tutorial

Comment (sjonany) [reply extension/lib/time_tracker_view.js:131]: yay!

File: extension/content_script.js (hunk 6 above)
Comment (sjonany) [reply extension/content_script.js]: Ooh very nice!

File: extension/background.js [hunk 8]
```diff
@@ -16,39 +16,39 @@ chrome.runtime.onInstalled.addListener(function() {
...
+    // Redirect user to a demo page, and auto-start the app there.
+	let demoUrl = 'https://en.wikipedia.org/wiki/Reading';
 	chrome.tabs.create({
 	    url: demoUrl,
 	    active: true
 	}, function(tab) {
-		chrome.tabs.sendMessage(tab.id, {command: "toggleUI"}, function(response) {});
+        // Have to wait for new tab to load; see: https://stackoverflow.com/questions/5816373/chrome-tab-create-and-tab-getselected
+        /* TODO: Change this from this obv super hacky strategy. 
+        Problem is: Only want to sendMessage once, AFTER the new tab is loaded. If do nothing, it sends the message to old page,
```
Comment (sjonany) [inline extension/background.js:32]: one way to do this: send a message back from content script to background, that's how u know it's loaded
**pretty sure u can do this, but havent tried.

Comment (sjonany) [reply extension/background.js:32]: TODO: is fine.

Comment (sjonany) [reply extension/background.js:32]: Option 2: save in settings "have seen tutorial?"
This has the advantage that you can control tutorial completeness check.
e.g. keep reshowing tutorial until user has completed a task.

Comment (sjonany) [reply extension/background.js:32]: O but leave this in next CL, cos this is big enough.

File: extension/background.js (hunk 2 above)
Comment (sjonany) [reply extension/background.js:56]: Very nice!

File: extension/content_script.js (hunk 3 above)
Comment (sjonany) [reply extension/content_script.js:279]: Nice catch!

File: extension/content_script.js [hunk 9]
```diff
@@ -635,21 +640,64 @@ function toggleExtensionVisibility() {
...
+	chrome.runtime.onMessage.addListener(	
+		function(request, sender, sendResponse) {	
+			if (request.command === "startTutorial") {	
+				$(tutorialPopupHtml).insertAfter($("body").children().first());
+				let tutorialPopup = $("#tutorialPopupContainer");
+				$(".popupCheckmark").css("background-image", "url("+popupCheckmarkUrl+")").click(function() {
+					$("#optionsButton").click();
+					tutorialPopup.remove()
+				});
+				$("#optionsButtonTutorial").click(function() {
```
Comment (sjonany) [inline extension/content_script.js:686]: I wonder how the UI will look like if user just clicks on the gear icon directly. -- should autoclose instruction probably?
If that case is not handled, please leave a todo.

**Review by sjonany — CHANGES_REQUESTED** [review]

File: extension/background.js (hunk 8 above)
Comment (benfrancis314) [reply extension/background.js:32]: I love option 2; I'm not sure that will help the "wait for new tab to be open" problem though? Adding TODO either way

File: extension/content_script.js (hunk 9 above)
Comment (benfrancis314) [reply extension/content_script.js:686]: If you mean the normal gear (not the one in instructions), no bc wasn't sure what we'd want anyway, but good point, adding todo

Comment (sjonany) [reply extension/content_script.js:686]: yeah sorry i meant normal gear, because I could see myself doing that.
Instead of "click tick", the resolving action would be "click gear"
todo sg.

Comment (sjonany) [reply extension/content_script.js:686]: ** and maybe tick isn't even necessary.
tick clicked -> instruction pops up 
vs
gear clicked -> instruction pops up

might as well have them learn the real flow = second flow

**Review by sjonany — APPROVED** [review]

File: extension/content_script.js (hunk 9 above)
Comment (benfrancis314) [reply extension/content_script.js:686]: Good point! Have tutorial progress when they do things, not by clicking on checkmark
